name: "Platform Independent Checks"
description: "Perform all platform independent checks"
inputs:
  PROJECT_PATH:
    description: "Path where the project is checked out"
    required: true
    default: "project"
  CONTROL_COMPONENTS_PATH:
    description: "Path to the control components library"
    required: true
    default: "project"
runs:
  using: "composite"
  steps:
    - name: Check Code Formatting
      run: "${{ inputs.CONTROL_COMPONENTS_PATH }}/scripts/check_format.sh"
      shell: bash
      env:
        PROJECT_PATH: "${{ inputs.PROJECT_PATH }}"

    - name: Check License Headers
      run: "${{ inputs.CONTROL_COMPONENTS_PATH }}/scripts/check_license.sh"
      shell: bash
      env:
          PROJECT_PATH: "${{ inputs.PROJECT_PATH }}"
          CONTROL_COMPONENTS_PATH: "${{ inputs.CONTROL_COMPONENTS_PATH }}"
