name: ESP32

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # `actions:write` permission is required to delete caches
      #
      # refs:
      #  - https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
      #  - https://github.com/actions/cache/blob/6849a6489940f00c2f30c0fb92c6274307ccb58a/tips-and-workarounds.md?plain=1#L57
      #  - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
      actions: write
    env:
      PROJECT_PATH: project
      IDF_PATH: esp-idf
      IDF_VERSION: v5.3.1
      CONFIGURATION_PATH_CCACHE: .env/ccache
      CONFIGURATION_PATH_UNIT_TESTS: .env/esp32_configuration_unit_tests
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.PROJECT_PATH }}

      - name: fmt check formatting
        uses: ./project/.github/actions/core/fmt
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
          CONTROL_COMPONENTS_PATH: ${{ env.PROJECT_PATH }}

      - name: esp32 setup env
        uses: ./project/.github/actions/esp32/env
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          IDF_VERSION: ${{ env.IDF_VERSION }}

      - name: system setup env
        uses: ./project/.github/actions/system/env

      - name: system setup ccache
        uses: ./project/.github/actions/system/ccache
        with:
          GITHUB_TOKEN: ${{ github.token }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
          CONTROL_COMPONENTS_PATH: ${{ env.PROJECT_PATH }}
          CONFIGURATION_PATH_CCACHE: ${{ env.CONFIGURATION_PATH_CCACHE }}

      - name: core format firmware build version
        id: version_formatter
        uses: ./project/.github/actions/core/version

      - name: unittests prepare configuration
        shell: bash
        run: |
          echo "CONFIG_OCS_UNIT_TEST_NETWORK_WIFI_ENABLED=y" >> ${{ env.CONFIGURATION_PATH_UNIT_TESTS }}
          echo "CONFIG_OCS_CORE_FW_VERSION=\"${{ steps.version_formatter.outputs.build_version }}\"" >> ${{ env.CONFIGURATION_PATH_UNIT_TESTS }}
          echo "CONFIG_OCS_CORE_FW_NAME=\"unittests\"" >> ${{ env.CONFIGURATION_PATH_UNIT_TESTS }}

      - name: unittests build
        uses: ./project/.github/actions/esp32/project
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tests
          CONFIGURATION_PATH_CCACHE: ${{ env.CONFIGURATION_PATH_CCACHE }}
          CONFIGURATION_PATH_PROJECT: ${{ env.CONFIGURATION_PATH_UNIT_TESTS }}

      - name: ds18b20-verifier build
        uses: ./project/.github/actions/esp32/project
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/ds18b20-verifier

      - name: ds-rom-code-scanner build
        uses: ./project/.github/actions/esp32/project
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/ds-rom-code-scanner

      - name: sht41-verifier build
        uses: ./project/.github/actions/esp32/project
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/sht41-verifier

      - name: unittests upload
        uses: ./project/.github/actions/esp32/upload
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tests
          PROJECT_ID: unittests

      - name: ds18b20-verifier upload
        uses: ./project/.github/actions/esp32/upload
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/ds18b20-verifier
          PROJECT_ID: ds18b20-verifier

      - name: ds-rom-code-scanner upload
        uses: ./project/.github/actions/esp32/upload
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/ds-rom-code-scanner
          PROJECT_ID: ds-rom-code-scanner

      - name: sht41-verifier upload
        uses: ./project/.github/actions/esp32/upload
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/sht41-verifier
          PROJECT_ID: sht41-verifier
