name: ESP32

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - name: "unittest"
            config: ".env/unittest_configuration"

          - name: "ds18b20-verifier"
            config: ".env/ds18b20_verifier_configuration"

          - name: "ds-rom-code-scanner"
            config: ".env/ds_rom_code_scanner_configuration"

          - name: "sht41-verifier"
            config: ".env/sht41_verifier_configuration"
    env:
      SOURCE_PATH: project
      IDF_PATH: esp-idf
      IDF_VERSION: v5.3.1
      CONFIGURATION_PATH_CCACHE: .env/ccache
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.SOURCE_PATH }}

      - name: check formatting
        uses: ./project/.github/actions/core/fmt
        with:
          PROJECT_PATH: ${{ env.SOURCE_PATH }}/projects/${{ matrix.project.name }}
          CONTROL_COMPONENTS_PATH: ${{ env.SOURCE_PATH }}

      - name: setup ESP32 environment
        uses: ./project/.github/actions/esp32/env
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          IDF_VERSION: ${{ env.IDF_VERSION }}

      - name: setup system environment
        uses: ./project/.github/actions/system/env

      - name: setup ccache
        uses: ./project/.github/actions/system/ccache
        with:
          CONFIGURATION_PATH_CCACHE: ${{ env.CONFIGURATION_PATH_CCACHE }}

      - name: format firmware build version
        id: version_formatter
        uses: ./project/.github/actions/core/version

      - name: prepare configuration
        uses: ./project/.github/actions/core/config
        with:
          PROJECT_NAME: ${{ matrix.project.name }}
          BUILD_VERSION: ${{ steps.version_formatter.outputs.build_version }}
          BUILD_CONFIG_PATH: ${{ matrix.project.config }}
          PROJECT_CONFIG_PATH: ${{ env.SOURCE_PATH }}/projects/config.yml

      - name: build firmware
        uses: ./project/.github/actions/esp32/project
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.SOURCE_PATH }}/projects/${{ matrix.project.name }}
          CONFIGURATION_PATH_CCACHE: ${{ env.CONFIGURATION_PATH_CCACHE }}
          CONFIGURATION_PATH_PROJECT: ${{ matrix.project.config }}

      - name: upload firmware
        uses: ./project/.github/actions/esp32/upload
        with:
          PROJECT_PATH: ${{ env.SOURCE_PATH }}/projects/${{ matrix.project.name }}
          PROJECT_NAME: ${{ matrix.project.name }}
          BUILD_VERSION: ${{ steps.version_formatter.outputs.build_version }}
