name: ESP32

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # `actions:write` permission is required to delete caches
      #
      # refs:
      #  - https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac
      #  - https://github.com/actions/cache/blob/6849a6489940f00c2f30c0fb92c6274307ccb58a/tips-and-workarounds.md?plain=1#L57
      #  - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
      actions: write
    env:
      PROJECT_PATH: project
      IDF_PATH: esp-idf
      IDF_VERSION: v5.3.1
      CONFIGURATION_PATH_CCACHE: .env/ccache
      CONFIGURATION_PATH_UNIT_TESTS: .env/esp32_configuration_unit_tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.PROJECT_PATH }}

      - name: Setup Prerequisites
        uses: ./project/.github/actions/basic_env
        with:
          GITHUB_TOKEN: ${{ github.token }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
          OCS_COMPONENTS_PATH: ${{ env.PROJECT_PATH }}
          CONFIGURATION_PATH_CCACHE: ${{ env.CONFIGURATION_PATH_CCACHE }}

      - name: Setup ESP-IDF
        uses: ./project/.github/actions/esp32_env
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          IDF_VERSION: ${{ env.IDF_VERSION }}

      - name: Perform All Checks
        uses: ./project/.github/actions/basic_checks
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}
          OCS_COMPONENTS_PATH: ${{ env.PROJECT_PATH }}

      - name: Format firmware build version
        id: version_formatter
        uses: ./project/.github/actions/format_build_version

      - name: Prepare Configuration for Unit Tests Build
        run: |
          echo "CONFIG_OCS_UNIT_TEST_NETWORK_WIFI_ENABLED=y" >> ${{ env.CONFIGURATION_PATH_UNIT_TESTS }}
          echo "CONFIG_OCS_CORE_FW_VERSION=\"${{ steps.version_formatter.outputs.build_version }}\"" >> ${{ env.CONFIGURATION_PATH_UNIT_TESTS }}
          echo "CONFIG_OCS_CORE_FW_NAME=\"unittest\"" >> ${{ env.CONFIGURATION_PATH_UNIT_TESTS }}
        shell: bash

      - name: Build Unit Tests
        uses: ./project/.github/actions/esp32_build
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tests
          CONFIGURATION_PATH_CCACHE: ${{ env.CONFIGURATION_PATH_CCACHE }}
          CONFIGURATION_PATH_PROJECT: ${{ env.CONFIGURATION_PATH_UNIT_TESTS }}

      - name: Build DS18B20 Verifier
        uses: ./project/.github/actions/esp32_build
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/ds18b20-verifier

      - name: Build DS Rom Code Scanner
        uses: ./project/.github/actions/esp32_build
        with:
          IDF_PATH: ${{ env.IDF_PATH }}
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/ds-rom-code-scanner

      - name: Upload Unit Tests Artifacts
        uses: ./project/.github/actions/esp32_upload
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tests
          PROJECT_ID: artifacts-unittests

      - name: Upload DS18B20 Verifier Artifacts
        uses: ./project/.github/actions/esp32_upload
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/ds18b20-verifier
          PROJECT_ID: artifacts-ds18b20-verifier

      - name: Upload DS Rom Code Scanner Artifacts
        uses: ./project/.github/actions/esp32_upload
        with:
          PROJECT_PATH: ${{ env.PROJECT_PATH }}/tools/ds-rom-code-scanner
          PROJECT_ID: artifacts-ds-rom-code-scanner
